name: Local Minima
description: My personal repository of musings and ideas...
pygments: true
markdown: kramdown

navigation:
- text: Blog
  url: /index.html
- text: About
  url: /about/index.html
- text: Code
  url: https://github.com/jfarid27

